[build]
  command = "cd exampleSite && hugo --gc --minify -D -b https://blowfish.page"
  publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.155.3"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"